### PR TITLE
Updated AnalyticalCard.test.tsx

### PR DESCRIPTION
**Pull request by kajal1811**
Rewrited test from enzyme to react-testing-library. Please, review the changes and give a confirmation.

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [ ] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Review by MarcusNotheis — CHANGES_REQUESTED** [review]
Thanks for your contribution, coding looks fine. Can you please update the test snapshot as well by running `yarn test -u`?
Thanks!

**Comment by kajal1811** [comment]
Sir, can you explain in detail how to run test snapshot?

**Comment by MarcusNotheis** [comment]
Basically you have to checkout the project, make sure you have Node.JS 14 and Yarn installed (as mentioned in our [Developer Guide](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md)). Then you can run `yarn test` in order to execute the tests. This will fail because the expected HTML Snapshot of the `AnalyticalCard` does not match the new result provided by the react-testing-library, so you will have to run `yarn test -u` in order to update the snapshots.
I saw you've created another pull request in #884 with some snapshot changes - please apply the snapshot update on top of this branch. I'll close the other PR.

Thanks!

**Comment by kajal1811** [comment]
Actually I am new to react and for this issue I basically forked that particular file and edited there and then did PR. So, I need to run the whole project using Node.js and Yarn on my laptop too, right?

**Comment by MarcusNotheis** [comment]
Yes, exactly :)

**Comment by kajal1811** [comment]
Can you please explain me in detail/step-by-step procedure to make project available on my localhost?

**Comment by MarcusNotheis** [comment]
I've just added a couple of sentences to our [developer guide](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md) that should explain all necessary steps. And please go through our [contribution guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) as well.

**Comment by MarcusNotheis** [comment]
merged with #897

**Pull request closed without merging**
