### PR TITLE
chore(base): create type definitions for theme configuration

### PR DESCRIPTION
**Pull request by Psidium**
Hey, following what I've seen in #1057 and #1136, I believe we could follow the same approach we did for  `UI5Devices.d.ts` and create a type definition for the base Theming config. 

I'm using these types in my project (internally at SAP).

I created the themes as an interface only so the user can use https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation to add a new theme in their project without disrupting the already established themes, like so:

```ts
declare module "@ui5/webcomponents-base/dist/config/Theme" {
  export interface ThemeKeys {
    my_new_theme: never;
  }
}
```

The only issue is with the themes themselves, since that when a new theme is created this file here will have to be updated.

### CODE REVIEW

**Comment by Psidium** [comment]
Another option would be to 

```ts
import { Themes } from "../../main/src/dist/Themes";

declare module "@ui5/webcomponents-base/dist/config/Theme" {
    export function getTheme(): Themes;
    export function setTheme(theme: Themes): void;
}
```

**Comment by MarcusNotheis** [comment]
Hey @Psidium,
thanks for creating this PR! I tried to take this one step further and integrate the type definitions directly in the UI5 Web Components Repo: https://github.com/SAP/ui5-webcomponents/pull/3653
Let's see if the Web Components PR will be accepted, otherwise we can go on and merge this one 🙂

**Comment by Psidium** [comment]
Regarding the `getTheme` function... shouldn't I use `useTheme` from the container used in `ThemeProvider` so that my component is aware of theme changes?

**Comment by MarcusNotheis** [comment]
Thanks for kicking this off, @Psidium! I just added `string` as allowed value for the setTheme function as well so that custom themes via SAP Theme Designer are supported as well.

**Review by MarcusNotheis — APPROVED** [review]

**Pull request merged**
