### PR TITLE
docs: deploy v1, v2 and nightly

### PR DESCRIPTION
**Pull request by MarcusNotheis**

### CODE REVIEW

**Review by Lukas742 — APPROVED** [review]

**Comment by lance315** [comment]
Hi @MarcusNotheis ,
Is v2 equals to nightly?

**Comment by MarcusNotheis** [comment]
Hi @lance315,
more or less yes.
The `nightly` documentation is build based on every commit to `main`, the `v2` is based on the release candidates of our `2.0.0` version:
https://sap.github.io/ui5-webcomponents-react/nightly/
https://sap.github.io/ui5-webcomponents-react/v2/

**Comment by lance315** [comment]
So is v2 stable or still an unstable version?

**Comment by MarcusNotheis** [comment]
It's mostly stable, except for the `FilterBar` component which might receive one more breaking change. We'll finally release it as stable 2.0.0 this month

**Pull request merged**
