### PR TITLE
Spinner-test-update

### PR DESCRIPTION
**Pull request by sidram05**
Spinner test update using react-testing-library

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [x] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Review by MarcusNotheis — APPROVED** [review]
Thanks for your contribution! Looks good to me

**Review by MarcusNotheis — CHANGES_REQUESTED** [review]
Ah sorry I forgot one thing: You need to update the snapshot files by running `yarn test -u TEST_NAME`, e.g. `yarn test -u Spinner` in this case to update the snapshots. Then we can merge it :)

**Comment by sidram05** [comment]
> Ah sorry I forgot one thing: You need to update the snapshot files by running `yarn test -u TEST_NAME`, e.g. `yarn test -u Spinner` in this case to update the snapshots. Then we can merge it :)

Tried to run this command but receiving the follow error, any thoughts ?
yarn-error

**Comment by MarcusNotheis** [comment]
Hey @sidram05,
you need to install `yarn` first: https://classic.yarnpkg.com/lang/en/

**Comment by sidram05** [comment]
> Hey @sidram05,
> you need to install `yarn` first: https://classic.yarnpkg.com/lang/en/

Hey @MarcusNotheis I am able to see the yarn version but not able to run the yarn command

yarn-error

**Comment by MarcusNotheis** [comment]
> > Hey @sidram05,
> 
> > you need to install `yarn` first: https://classic.yarnpkg.com/lang/en/
> 
> 
> 
> Hey @MarcusNotheis I am able to see the yarn version but not able to run the yarn command
> 
> yarn-version
> 
> 
> 
> 

This might sound like "best of IT support", but have you tried to restart your computer? If this doesn't help, can you try to re install yarn one more time?

**Comment by sidram05** [comment]
> > > Hey @sidram05,
> > 
> > 
> > > you need to install `yarn` first: https://classic.yarnpkg.com/lang/en/
> > 
> > 
> > Hey @MarcusNotheis I am able to see the yarn version but not able to run the yarn command
> > yarn-version
> 
> This might sound like "best of IT support", but have you tried to restart your computer? If this doesn't help, can you try to re install yarn one more time?

I did a restart it seems to detect yarn now but shows the following error message when I try to run the command **yarn test -u Spinner**

>>yarn-message2

**Comment by MarcusNotheis** [comment]
Great :) you have to run the command from the root of the project, so in your case in ....\GitHub\ui5-webcomponents-react.

**Comment by sidram05** [comment]
> Great :) you have to run the command from the root of the project, so in your case in ....\GitHub\ui5-webcomponents-react.

Tried to run the command from root, also performed **npm install** at root level but seeing the following error 

Sorry to bother you by back to back screenshots

Yarn-Error2

**Comment by MarcusNotheis** [comment]
No worries :) 
You have to use yarn for everything, so could you please delete on root level the `package-lock.json` file and all `node_modules`? Then run `yarn install` followed by `yarn test -u Spinner`. This should give you the expected result (There should be a changed snapshot file after running those command, and that the one you would have to commit)

**Comment by sidram05** [comment]
> No worries :)
> You have to use yarn for everything, so could you please delete on root level the `package-lock.json` file and all `node_modules`? Then run `yarn install` followed by `yarn test -u Spinner`. This should give you the expected result (There should be a changed snapshot file after running those command, and that the one you would have to commit)

Finally was able run **yarn install** successfully  but while running **yarn test -u Spinner** seeing the following error

yarn-testError

**Comment by MarcusNotheis** [comment]
Looks like you have some bad dependencies in your project? Actually we don't have any dependency on @types/mocha.
Can you try to run the following scripts?
```sh
npx lerna clean -y
```
then, delete the node_modules folder on root again
and then again
```sh
yarn install
yarn test -u Spinner
```

**Comment by sidram05** [comment]
> ```shell
> npx lerna clean -y
> ```

Performed the above changes , got successful yarn build and ran **"yarn test -u Spinner"** is this success message ?

Yarntest

**Comment by MarcusNotheis** [comment]
We are coming closer :) 
Something is wrong with the Spinner thing, can you try `yarn test -u`?

**Comment by sidram05** [comment]
> We are coming closer :)
> Something is wrong with the Spinner thing, can you try `yarn test -u`?

This is what I see for **yarn test -u**
yarntestU

**Comment by MarcusNotheis** [comment]
Looks like jest is not finding the test files. Do you have everything commited in your branch? Then I would try to run the tests by myself to see whats wrong

**Comment by sidram05** [comment]
> Looks like jest is not finding the test files. Do you have everything commited in your branch? Then I would try to run the tests by myself to see whats wrong

I have changes in the yarn.lock and package.json files do you want me to commit them to the branch ?

**Comment by MarcusNotheis** [comment]
mhmm changes in package.json sounds wrong to be honest, there should be no changes required in package.json. Then I'll try to run the tests with the current state :)

**Comment by sidram05** [comment]
> mhmm changes in package.json sounds wrong to be honest, there should be no changes required in package.json. Then I'll try to run the tests with the current state :)

Sorry there are no changes in package.json my bad was looking at an old branch, I have committed my changes please have a look and let me know, thanks for taking the time..

**Comment by MarcusNotheis** [comment]
Hey @sidram05,
I figured out there was a bad jest config which didn't work on windows.
I just updated it as well as the snapshot, so we are good to merge here :) 
For all the other issues, you can then create a new branch from master as soon as this is merged and then you should be able to just run `yarn test -u` for all the other tests :)

**Review by MarcusNotheis — APPROVED** [review]

**Pull request merged**
