### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

Do not merge! There’s a “1” in the translation, which imo shouldn’t be there. I’ll check on Monday

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Review by Lukas742 — APPROVED** [review]

**Pull request merged**
